name: CD Pipeline - Deploy to EC2

on:
  push:
    branches: ["master"]
    paths:
      - "docker-compose.prod.yml"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps Repo
        uses: actions/checkout@v4

      - name: Setup SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_PRIVATE_KEY }}" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H 13.127.215.4  >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -i ~/.ssh/deploy_key ubuntu@13.127.215.4 \
            -o StrictHostKeyChecking=no \
            "DOCKERHUB_USERNAME='$DOCKERHUB_USERNAME' DOCKERHUB_TOKEN='$DOCKERHUB_TOKEN' GITOPS_PAT='$GITOPS_PAT' bash -s" << 'EOF'
            set -e
            GITOPS_DIR="/home/ubuntu/syook-encryption-gitops"
            REPO_URL="https://${GITOPS_PAT}@github.com/prashant-kiit/syool--encryption-application-gitops.git"

            if [ ! -d "$GITOPS_DIR" ]; then
              git clone "$REPO_URL" "$GITOPS_DIR"
            else
              cd "$GITOPS_DIR"
              git remote set-url origin "$REPO_URL"
              git pull origin master
            fi

            cd "$GITOPS_DIR"

            echo "$DOCKERHUB_TOKEN" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin
            docker compose -f docker-compose.prod.yml pull
            docker compose -f docker-compose.prod.yml up -d --remove-orphans
            docker image prune -f
          EOF
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
          GITOPS_PAT: ${{ secrets.GITOPS_PAT }}

      - name: Verify Deployment
        run: |
          ssh -i ~/.ssh/deploy_key ubuntu@13.127.215.4  << 'EOF'
            cd /home/ubuntu/syook-encryption-gitops
            docker compose -f docker-compose.prod.yml ps
          EOF